In [1]:
import pandas as pd

In [10]:
import numpy as np

In [2]:
dataset = pd.read_csv('/databisnis.csv');

In [3]:
dataset

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2021                     Level 1                99999   
1      2021                     Level 1                99999   
2      2021                     Level 1                99999   
3      2021                     Level 1                99999   
4      2021                     Level 1                99999   
...     ...                         ...                  ...   
41710  2013                     Level 3                 ZZ11   
41711  2013                     Level 3                 ZZ11   
41712  2013                     Level 3                 ZZ11   
41713  2013                     Level 3                 ZZ11   
41714  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01   
1                  All industries  Dollars (millions)           H04   
2                  All industries  Dollars (millions)           H05   
3                  All industries  Dollars (millions)           H07   
4                  All industries  Dollars (millions)           H08   
...                           ...                 ...           ...   
41710  Food product manufacturing          Percentage           H37   
41711  Food product manufacturing          Percentage           H38   
41712  Food product manufacturing          Percentage           H39   
41713  Food product manufacturing          Percentage           H40   
41714  Food product manufacturing          Percentage           H41   

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance   
1      Sales, government funding, grants and subsidies  Financial performance   
2                    Interest, dividends and donations  Financial performance   
3                                 Non-operating income  Financial performance   
4                                    Total expenditure  Financial performance   
...                                                ...                    ...   
41710                                      Quick ratio       Financial ratios   
41711              Margin on sales of goods for resale       Financial ratios   
41712                                 Return on equity       Financial ratios   
41713                           Return on total assets       Financial ratios   
41714                            Liabilities structure       Financial ratios   

         Value                             Industry_code_ANZSIC06  
0      757,504  ANZSIC06 divisions A-S (excluding classes K633...  
1      674,890  ANZSIC06 divisions A-S (excluding classes K633...  
2       49,593  ANZSIC06 divisions A-S (excluding classes K633...  
3       33,020  ANZSIC06 divisions A-S (excluding classes K633...  
4      654,404  ANZSIC06 divisions A-S (excluding classes K633...  
...        ...                                                ...  
41710       52  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41711       40  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41712       12  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41713        5  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41714       46  ANZSIC06 groups C111, C112, C113, C114, C115, ...  

[41715 rows x 10 columns]

In [4]:
dataset.head(8)

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2021                     Level 1                99999       All industries   
1  2021                     Level 1                99999       All industries   
2  2021                     Level 1                99999       All industries   
3  2021                     Level 1                99999       All industries   
4  2021                     Level 1                99999       All industries   
5  2021                     Level 1                99999       All industries   
6  2021                     Level 1                99999       All industries   
7  2021                     Level 1                99999       All industries   

                Units Variable_code  \
0  Dollars (millions)           H01   
1  Dollars (millions)           H04   
2  Dollars (millions)           H05   
3  Dollars (millions)           H07   
4  Dollars (millions)           H08   
5  Dollars (millions)           H09   
6  Dollars (millions)           H10   
7  Dollars (millions)           H11   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   
3                             Non-operating income  Financial performance   
4                                Total expenditure  Financial performance   
5                           Interest and donations  Financial performance   
6                                   Indirect taxes  Financial performance   
7                                     Depreciation  Financial performance   

     Value                             Industry_code_ANZSIC06  
0  757,504  ANZSIC06 divisions A-S (excluding classes K633...  
1  674,890  ANZSIC06 divisions A-S (excluding classes K633...  
2   49,593  ANZSIC06 divisions A-S (excluding classes K633...  
3   33,020  ANZSIC06 divisions A-S (excluding classes K633...  
4  654,404  ANZSIC06 divisions A-S (excluding classes K633...  
5   26,138  ANZSIC06 divisions A-S (excluding classes K633...  
6    6,991  ANZSIC06 divisions A-S (excluding classes K633...  
7   27,801  ANZSIC06 divisions A-S (excluding classes K633...

In [7]:
Year = dataset["Year"]

In [8]:
Year.head(5)

0    2021
1    2021
2    2021
3    2021
4    2021
Name: Year, dtype: int64

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41715 entries, 0 to 41714
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Year                         41715 non-null  int64 
 1   Industry_aggregation_NZSIOC  41715 non-null  object
 2   Industry_code_NZSIOC         41715 non-null  object
 3   Industry_name_NZSIOC         41715 non-null  object
 4   Units                        41715 non-null  object
 5   Variable_code                41715 non-null  object
 6   Variable_name                41715 non-null  object
 7   Variable_category            41715 non-null  object
 8   Value                        41715 non-null  object
 9   Industry_code_ANZSIC06       41715 non-null  object
dtypes: int64(1), object(9)
memory usage: 3.2+ MB


In [11]:
box1 = np.array([1,2,3,4])

In [12]:
box1

array([1, 2, 3, 4])

In [17]:
box2 = np.array([[1,2,3], [4,5,6]])

In [18]:
box2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])